export const ErrorCodes = {
  // scan errors
  SCAN_NOT_FOUND: 'SCAN_NOT_FOUND',
  SCAN_VALIDATION_FAILED: 'SCAN_VALIDATION_FAILED',
  SCAN_START_FAILED: 'SCAN_START_FAILED',

  SCAN_DELETE_FAILED: 'SCAN_DELETE_FAILED',

  // general
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};
